languages = [
    'AWS',
    'Bash/Shell',
    'C++',
    'COBOL',
    'Cassandra',
    'Clojure',
    'Crystal',
    'Delphi',
    'Django',
    'Drupal',
    'DynamoDB',
    'Elasticsearch',
    'Flask',
    'Flow',
    'Git',
    'Go',
    'Google Cloud Platform',
    'Hadoop',
    'Java',
    'JavaScript',
    'Kubernetes',
    'LISP',
    'MariaDB',
    'Microsoft Azure',
    'Node.js',
    'Oracle',
    'PHP',
    'Pandas',
    'Perl',
    'PowerShell',
    'Python',
    'Qt',
    'React.js',
    'Redis',
    'Ruby on Rails',
    'Rust',
    'Scala',
    'Swift',
    'Terraform',
    'TypeScript',
    'Unity 3D',
    'Vue.js',
    'Xamarin',
    'jQuery'
]